apiVersion: v1
kind: Pod
metadata:
  name: video-collect
  labels:
    app: video-collect
spec:
  containers:
  - name: vis
    image: 10.49.11.33:5000/library/viscom:v1.5-arm
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: dev-video0
      mountPath: /dev/video0
    - name: dev-video1
      mountPath: /dev/video1
    securityContext:
      privileged: true
  hostNetwork: true
  volumes:
  - name: dev-video0
    hostPath:
      path: /dev/video0
  - name: dev-video1
    hostPath:
      path: /dev/video1
  nodeSelector:
    kubernetes.io/hostname: video-collect 
